import Head from 'next/head'
import Header from "../components/Header";
import Footer from "../components/Footer";
import { container } from '../styles/Layout.module.css'


export default function Layout({ children }) {
  return (
    <div className={container}>
      <Head>
        <title>Forel v piter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  )
}
